export const arr = [
    {
      skill:"JavaScript",percent:"80",max:"100"      
      },
      {
        skill:"Angular",percent:"60",max:"100",     
        },
        {
          skill:"React.JS",percent:"85",max:"100",        
          },
          {
            skill:"Vue.JS",percent:"55",max:"100",       
            },
            {
              skill:"Bootstrap",percent:"59",max:"100",           
              },
              {
                skill:"PHP",percent:"65",max:"100",     
                },
                {
                  skill:"Node.JS & Express JS",percent:"75",max:"100",           
                  },
                  {
                    skill:"MySQL",percent:"55",max:"100",      
                    },
                    {
                      skill:"MongoDB",percent:"86",max:"100",         
                      },
                      {
                        skill:"Next.JS",percent:"60",max:"100",        
                        },
                        ,
                  {
                    skill:"Docker",percent:"65",max:"100",      
                    },   
                    {
                    skill:"Jenkins",percent:"60",max:"100",      
                      },   
                      {
                        skill:"Kubernetes",percent:"50",max:"100",      
                        }, 
                      {
                        skill:"Chef & Ansible",percent:"70",max:"100",      
                        },
                    {
                      skill:"AWS",percent:"57",max:"100",         
                      },
                      {
                        skill:"Python",percent:"70",max:"100",        
                        },
];